import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import { ConvexClinetProvider } from "@/providers/convex-client-provider";

const inter = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="shortcut icon" href="/images/logo.svg" type="image/x-icon" /></head>
      <body className={inter.className}>
        <ConvexClinetProvider>
          {children}
        </ConvexClinetProvider>
      </body>
    </html>
  );
}
